//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.04 at 03:58:33 PM CET 
//


package it.pjsoft.reactive.generic.transfer.model.msg;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Request_QNAME = new QName("http://www.eng.it/reactive/generic", "request");
    private final static QName _Content_QNAME = new QName("http://www.eng.it/reactive/generic", "content");
    private final static QName _Response_QNAME = new QName("http://www.eng.it/reactive/generic", "response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JaxbBodyPayload }
     * 
     */
    public JaxbBodyPayload createJaxbBodyPayload() {
        return new JaxbBodyPayload();
    }

    /**
     * Create an instance of {@link GenericResponse }
     * 
     */
    public GenericResponse createGenericResponse() {
        return new GenericResponse();
    }

    /**
     * Create an instance of {@link GenericRequest }
     * 
     */
    public GenericRequest createGenericRequest() {
        return new GenericRequest();
    }

    /**
     * Create an instance of {@link ResponseHeader }
     * 
     */
    public ResponseHeader createResponseHeader() {
        return new ResponseHeader();
    }

    /**
     * Create an instance of {@link ListBody }
     * 
     */
    public ListBody createListBody() {
        return new ListBody();
    }

    /**
     * Create an instance of {@link Features }
     * 
     */
    public Features createFeatures() {
        return new Features();
    }

    /**
     * Create an instance of {@link Feature }
     * 
     */
    public Feature createFeature() {
        return new Feature();
    }

    /**
     * Create an instance of {@link RequestHeader }
     * 
     */
    public RequestHeader createRequestHeader() {
        return new RequestHeader();
    }

    /**
     * Create an instance of {@link JaxbBody }
     * 
     */
    public JaxbBody createJaxbBody() {
        return new JaxbBody();
    }

    /**
     * Create an instance of {@link BinaryBody }
     * 
     */
    public BinaryBody createBinaryBody() {
        return new BinaryBody();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eng.it/reactive/generic", name = "request")
    public JAXBElement<GenericRequest> createRequest(GenericRequest value) {
        return new JAXBElement<GenericRequest>(_Request_QNAME, GenericRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JaxbBodyPayload }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eng.it/reactive/generic", name = "content")
    public JAXBElement<JaxbBodyPayload> createContent(JaxbBodyPayload value) {
        return new JAXBElement<JaxbBodyPayload>(_Content_QNAME, JaxbBodyPayload.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.eng.it/reactive/generic", name = "response")
    public JAXBElement<GenericResponse> createResponse(GenericResponse value) {
        return new JAXBElement<GenericResponse>(_Response_QNAME, GenericResponse.class, null, value);
    }

}
